added reducers and actions in the redux folder
Richez003/BOOKSTORES pull request #2
Opened 2022-06-21 06:14 UTC by Richez003

added reducer and actions.
used combined reducer functions.
linters passed. 
installed redux

2022-06-21 07:14 UTC, BenMukebo requested changes
### Hi @Richez003,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Good commit messages ✔️ 
- You have followed  JavaScript best practices. ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


- [ ]  Please, add a meaningful  `Project description`. Remember A project description is a high-level overview of why you're doing a project. The document explains a project's objectives and essential qualities. Is an essential document that provides your audience with a comprehensive overview of the project. Think of it as the elevator pitch that focuses on what and why without delving into how. 😉 💯 

- [ ] Please update your Readme, currently, some headings are missing such as  
```
## Acknowledgments

- Microverse
```
``` ##  License ``` section with the MIT license at the end of your README file to make it more professional. I would also recommend you add this. 😄  please refer to this [template](https://github.com/microverseinc/readme-template).

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly, get used to committing your code, A Git Commit Message helps identify all the changes in the documentation. When code is committed often, GIT can actually be more useful and can help you know what changes you have made for each step towards the complete feature. I would commit often and early, especially if you're on a team. Lack of commitment can often cause problems in fixing errors and putting more work into fixing them.

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-21 07:14 UTC, BenMukebo commented on src/redux/books/books.js
> +});
- [x] Great job so far 👏🏻 But what if we define ADD_BOOK and REMOVE_BOOK as action types ( Note: names can be slightly different) 🤔  and let's make sure the value of each action type follows the [ducks pattern](https://github.com/erikras/ducks-modular-redux), so it will be something like:  
- const ADD_BOOK = bookstore/books/ADD_BOOK and
- const REMOVE_BOOK = bookstore/books/REMOVE_BOOK

2022-06-21 07:14 UTC, BenMukebo commented on src/redux/categories/categories.js
> +const initialState = [];
- [x] Same here 🤔  what if we define CHECK_STATUS as action types ( Note: names can be slightly different)  and let's make sure the value of each action type follows the [ducks pattern](https://github.com/erikras/ducks-modular-redux), so it will be something like:  
- const CHECK_STATUS = bookstore/categories/CHECK_STATUS

- [x] Also consider to Creates and Exports **Action Creator**. (`checkStatus` function) as you did in the `redux/books/books.js`. so it will be something like:  
- ```
  export const checkStatus = (payload) => ({
    type: 'CHECK_STATUS',
    payload,
  });
```

2022-06-21 07:14 UTC, BenMukebo commented on src/redux/categories/categories.js
> +export default checkReducer;
- [ ]  In this milestone you have to configure your Redux Store, write actions and reducer for adding and removing books however, I'm getting this error message in the console when I'm trying to add or remove a book, Kindly fix this and make sure the user can add and a new book remove it from the list without any error 😜 👍🏻 

![21bad](https://user-images.githubusercontent.com/79058364/174737043-eec985e1-d27d-4cbf-9f2b-a4adeef1c70c.png)

2022-06-23 19:42 UTC, Richez003 commented on src/redux/books/books.js
> +});
done

2022-06-23 19:43 UTC, Richez003 commented on src/redux/categories/categories.js
> +const initialState = [];
done

2022-06-23 19:44 UTC, Richez003 commented on src/redux/categories/categories.js
> +export default checkReducer;
please the add and remove wasn't for this particular project. kindly check the requirement for this particular project again thanks

2022-06-23 20:17 UTC, DeliceLydia approved these changes
## Hi @Richez003, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 03:21 UTC, merged